---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
   - name: show run 
     ios_command:
       host: "{{ ansible_host }}"
       authorize: yes
       username: jason
       password: BLeASm0r
       auth_pass: BLeASm0r
       commands:
         - show run		 
     register: config

   - name: save output to /etc/ansible/backups 
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "show_run_{{ inventory_hostname }}.txt"
